name: test-workflow

on: 
 push: 
 workflow_dispatch: 

jobs:
  test-job:
    concurrency:
      group: test-job
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - name: welcome message
      run: |
        echo "welcome to Github Actions"
        echo "Hi Basava"

    - uses: actions/checkout@v3

    - name: list the files
      run: |
        ls -a
        sleep 600s
       

    - name: read the files

      run: cat .github/workflows/test.yml



